### ISSUE TITLE
Sim setup won't recognize a dictionary

### ISSUE THREAD

**Issue by avictorious** [fpsim/fpsim#121]
When you set up parameters with a dictionary and then pass them to a Sim, they aren't being recognized.   The following code seems like it should assign a sim with 1,000 to the location Kenya, but when you print the location of the sim that's set up, it is None and so defaults back to Senegal.  

base_pars = dict(location='kenya', n_agents=1000, verbose=0)
sim = fp.Sim(base_pars)

**Comment by cliffckerr** [comment]
that is a bit confusing! the reason is that location is not a parameter but a separate argument to the sim, i.e.
```
base_pars = dict(n_agents=n_agents, verbose=1)
sim = fp.Sim(base_pars, location='kenya')
```
alternatively, since the sim can take keyword arguments, you could also do
```
base_pars = dict(location='kenya', n_agents=n_agents, verbose=1)
sim = fp.Sim(**base_pars)
```
which is exactly equivalent to doing
```
sim = fp.Sim(location='kenya', n_agents=n_agents, verbose=1)
```
i'm not sure what the best solution is here...it is a 'gotcha' that the location can't be passed as a parameter as you noted. but what the location argument does is create a parameter dict, so it would kind of be a chicken-and-egg situation if it's a parameter itself...

**Comment by avictorious** [comment]
@cliffckerr Thanks for the clarification and looking through.  It makes sense that that pars are one parameter and the location is a second, separate parameter, so that's how I'll think about it.
