### ISSUE TITLE
Run manual calibration - Ethiopia

### ISSUE THREAD

**Issue by aaslinur** [fpsim/fpsim#162]
This issue documents this first manual calibration for Ethiopia using the new calibrate_manual.py script.

**Comment by aaslinur** [comment]
The follow changes were made to the calibrate_manual.py and parameters.py files for Ethiopia based on recent changes to the kenya.py file.

1. The basic parameters and duration sections of the ethiopia.py were updated to include: 

- 'short_int': 24,  # Duration of a short birth interval between live births in months

- 'low_age_short_int': 0,  # age limit for tracking the age-specific short birth interval

- 'high_age_short_int': 20,  # age limit for tracking the age-specific short birth interval


2. The fecundity and exposure section of ethiopia.py was updated to include:

- 'restrict_method_use': 0, # If 1, only allows agents to select methods when sexually active within 12 months

                                   # and at fated debut age.  Contraceptive matrix probs must be changed to turn on

**Comment by aaslinur** [comment]
![Image](https://github.com/fpsim/fpsim/assets/78984333/9c52aa9c-2e82-470b-bb27-8faa74407c8c)
![Image](https://github.com/fpsim/fpsim/assets/78984333/14ed2239-0141-4ee7-9e06-66952b928aa1)
![Image](https://github.com/fpsim/fpsim/assets/78984333/fcd29c9c-2a16-42c2-8949-3ec53d6d14c1)
![Image](https://github.com/fpsim/fpsim/assets/78984333/a4199746-865e-4298-9e28-3e99e0dea446)
![Image](https://github.com/fpsim/fpsim/assets/78984333/e0401b02-736a-4c25-b783-4e12b3b572a5)
![Image](https://github.com/fpsim/fpsim/assets/78984333/8b1afd77-60fa-4263-a956-dec6ce9c4670)
![Image](https://github.com/fpsim/fpsim/assets/78984333/e8fb1b7b-1c4c-48c0-b82c-864cf274da54)
![Image](https://github.com/fpsim/fpsim/assets/78984333/abdc7135-b9c8-40f9-90e4-5e1da4f37856)
![Image](https://github.com/fpsim/fpsim/assets/78984333/5da5ec92-eca0-4a04-865f-5f108ec9ce14)
![Image](https://github.com/fpsim/fpsim/assets/78984333/525b99cc-5171-468a-b023-bf01def31dac)
![Image](https://github.com/fpsim/fpsim/assets/78984333/7ab1cbcc-3af7-4991-b836-0d751bf80bdc)
![Image](https://github.com/fpsim/fpsim/assets/78984333/c2d02a04-01a1-43bf-bbe7-86fee65c3cf8)

**Comment by emilydriano** [comment]
The following fix was required to successfully generate the age-parity plots:
- renamed the skyscrapers plot from 'Diff: data - model' to 'Diff_data-model', as the colon character was preventing it from being saved in the figs directory. 
- Added logic that ensures a 'figs' directory is created under the location folder if it doesn't already exist (and if the do_save setting is set to true)

The following changes were made to the code to improve the calibrate_manual script:
- fixed the code to write the plots to the figs directory under '{country}/figs/' (rather than in the 'locations' directory)
- added more thorough comments at the top of the file describing the files required and the naming conventions expected
- shifted all the global var's to the top of the file that should either be evaluated or set by the user (to make it more intuitive what needs to be modified)
- shifted 'dataset' to be included in these user-defined variables, as it frequently causes an error when not updated correctly if calibrating to a new country. Also renamed it to 'skyscrapers_dataset' to be more intuitive.
- removed kenya-specific references from comments

**Comment by aaslinur** [comment]
Data file updated to reproduce the figure on contraceptive method use.

![Image](https://github.com/fpsim/fpsim/assets/78984333/b3093a95-de76-49b9-8914-9e9b1aace2a0)

**Comment by aaslinur** [comment]
Updated figures for manual calibration of FPsim-Ethiopia. Using auto-calibration script to further improve national level calibration. 

![Image](https://github.com/fpsim/fpsim/assets/78984333/028b9c43-f34c-4e96-b392-f32c2899d109)
![Image](https://github.com/fpsim/fpsim/assets/78984333/97207876-3e31-43cf-8239-9b984e633764)
![Image](https://github.com/fpsim/fpsim/assets/78984333/ae21e7ab-79eb-4fff-a24b-ab8ba152eaa4)
![Image](https://github.com/fpsim/fpsim/assets/78984333/f2ef40d9-799d-4647-bded-11630e9f6602)
![Image](https://github.com/fpsim/fpsim/assets/78984333/f1efb70e-78a0-47c0-ba9b-9b0bb37a150c)
![Image](https://github.com/fpsim/fpsim/assets/78984333/5fcdfeb5-a939-4dc4-b3b7-42ec0c7e4567)
![Image](https://github.com/fpsim/fpsim/assets/78984333/99316dcd-b24b-48c9-a0af-88604ab17dcd)
![Image](https://github.com/fpsim/fpsim/assets/78984333/e26e689b-1156-4eca-9fce-3726483259dc)
![Image](https://github.com/fpsim/fpsim/assets/78984333/970add3c-d3c3-43c2-aa6d-1a84a0531e00)
![Image](https://github.com/fpsim/fpsim/assets/78984333/46fe40a6-6091-4c03-9d9f-a841bde9f006)
![Image](https://github.com/fpsim/fpsim/assets/78984333/5cc1daf7-f8da-4e11-9c64-aa4d0b3bf239)
![Image](https://github.com/fpsim/fpsim/assets/78984333/d3e49281-eda4-4d1f-ba8b-cfc5ed3495b9)
![Image](https://github.com/fpsim/fpsim/assets/78984333/6f777bd1-1a1e-4de9-b09f-e9253a6aed16)
