### ISSUE TITLE
Implement new attributes about education (goals, attainment) 

### ISSUE THREAD

**Issue by pausz** [fpsim/fpsim#184]
Implement new attribute that captures how many years of education of a person has attained over the course of a simulation.  

Related issues:
#171 

From Marita:

> Thank you for all the work on this @pausz ! It's looking great. I have been thinking more about education and I think we should actually take a slightly different approach than I proposed before. Instead of having an education target, I think we can just use a probability of getting one more year of education each year. Each year on her birthday, the woman will either get one more year of education incremented or not. And the probability of that happening will be based on age and parity. For example: For a girl 15yo who has 6 years of education and parity 0, there is a xx% probability of having 7+ years of edu at age 16. I can pull a matrix from DHS that shows, by age and parity, the percentage that have each number of years of education. The DHS data will only start at age 15, so we will have to find a way to work backwards and recreate the years from start of edu to age 15. Does this approach make sense to you? We can talk through it more in our next meeting, and I will also pull the data before that to see what it looks like. I think this approach should be easier to match the data as well (as long as the age or parity distribution doesn't change much).

**Comment by mzimmermann-IDM** [comment]
@pausz FYI I didn't forget about this! I was looking into the questions you brought up and realized I calculated the conditional probabilities wrong. I am trying to figure out a correct way to do it. Will let you know next week.

**Comment by mzimmermann-IDM** [comment]
Update on the education data. I think we might have to go with a different approach based on the way the data looks. It would be great to talk this through. I looked at education by age in the Kenya DHS data. I had done this with parity too, but for simplicity let's look at just age first. Also for this discussion I didn't include young women because that also adds complexity. 

This is a plot of educational trajectories if you increased education every year. I think the middle right panel (edu_at_15) is a good example. This line shows the percentage of 15 year olds that have 7 years of edu, then 16 yo that have 8 years of edu, 17 yo with 9 years of edu, etc. 
![image](https://github.com/fpsim/fpsim/assets/48844053/008d9348-09d0-4dc5-ab6e-0bdc0f84b221)

I would expect this line to be decreasing, as more women stop education each year. You can see that this is not necessarily the case. What this means is that for some ages, we get a >100% conditional probability for continuing education, which of course won't work. 

I thought perhaps this was due to not having a big enough sample size, so I combined many countries just to see what it would look like. The lines smooth out a bit, but we still see the same issue.
![image](https://github.com/fpsim/fpsim/assets/48844053/ca536168-9d33-45ec-a4c5-28304792cd10)

My best guess is that the issue is because this is a cross sectional sample, these women had all started school at a different time, and educational attainment expectations changed over that time frame. I think that we will have to go back to the original idea of having an educational goal, and having a boolean for in education or not  that year. I have not yet figured out how to parameterize that from the data, but am going to start working on it. 

It will be great to talk more about this and hear others' thoughts.

**Comment by mzimmermann-IDM** [comment]
Next attempt: check if we could use the longitudinal PMA data instead. Unfortunately, that was collected in 2019-2021... right during covid. In wave 2, more than half of girls said their school had closed due to covid, and of those 40% still hadn't reopened. Bad timing, so I don't think we can use that data. On to the next idea.

**Comment by mzimmermann-IDM** [comment]
Ok, new proposal (which is basically back to our original idea. Each woman gets an education goal. This is parameterized based on the distribution of education for women over age 20 with no children, stratified by urban/rural from DHS. I'm still very hesitant about this being the goal, so open to other ideas here. 
![image](https://github.com/fpsim/fpsim/assets/48844053/418f86f2-7af0-4165-96da-4a9165134f28)

We can initialize based on the distribution of education from DHS. Here's what it looks like:
![image](https://github.com/fpsim/fpsim/assets/48844053/8de98acd-30ee-403e-bc90-a8c11b562d16)
And I added what some smoothing and extrapolation could potentially look like.
![image](https://github.com/fpsim/fpsim/assets/48844053/d98c38a8-6ebe-409d-a05f-5e7c37e62e6c)

We assume education continues increasing by 1 each year until they reach their goal or age 18, whichever comes first. If she gets pregnant before age 18, there is a probability of stopping education. In PMA, of women with a first birth before age 18, 12.6% stopped education within 1 year of that birth. Of women who had a subsequent (not first) birth before age 18, 14.1% stopped school within 1 year of that birth. The biggest assumption here are 1: if you stop school for a birth, you don't restart; and 2: there are no other non-pregnancy related interruptions in education. How do we feel about these assumptions? If we agree on this, what format would be easiest to have this data in? We can discuss in our next meeting. (cc @MObrien-IDM )

**Comment by pausz** [comment]
Re data format, I think csv files would be fine. We can load them into arrays in `kenya.py` as it's done for other parameters. 

About assumptions on keep education dynamics: 

1. stop/resume education: if a woman stop school for a (first) birth, she doesn't resume education is modelling the "worst case scenario" so we would expect to see poorer education outcomes than what we observe in real-world data. As a first step to get an education MVP, this assumption could be fine. 

I  think it should not be too difficult (this will come back to haunt me later :sweat_smile:)  to add a restart mechanism post-pregnancy, provided that the woman had not yet achieved her education goal  -- I had added something like that in the first prototype of education. This assumption would now be "best case scenario" because if a woman has multiple pregnancies she would have her education interrupted multiple times, but wouldn't drop out. To get the nuance of real-world data, we'd need (parity, age) probabilities of dropping out (PMA data) that Marita suggested.    
     

2. to keep things simple, at least to begin with, having only pregnancy-related interruptions in education seems ok to me.  

We can refine the logic of education interruptions in future iterations. For instance I can imagine that having paid employment during school age may increases the probability of dropping out of school before reaching the education goal, but I wouldn't add that in the first iteration of education dynamics.

**Comment by mzimmermann-IDM** [comment]
@pausz there are now tree csv files added to my branch. You should be able to use them now. They are for education initialization (by age), objective, and probability of stopping due to pregnancy (by age and parity). Let me know if any of them are unclear or if you would like them formatted any differently. It is easy for me to change if so.

My last to do on the issue is to look into the literature to verify the assumption that 100% of women have an interruption in edu when they give birth, and see if there is any literature about when they restart (if they do0.

**Comment by pausz** [comment]
@mzimmermann-IDM In the csv files with edu data, could all values be exported as either floats or integers --except where we have NA? I don't know how R decides on which type to use, but in `edu_objective.csv` the columns `age` and `urban` are strings:
![image](https://github.com/fpsim/fpsim/assets/1563810/92236bb3-6e9e-403a-803c-f7edd93cff8b)

while in `edu_initialization.csv` `age` and `edu` are integers and floats respectively. 

It's not a big deal as I can convert them when I load them, but it'd be simpler if we don't have to do any type conversion steps.
