### ISSUE TITLE
Make empowerment optional

### ISSUE THREAD

**Issue by cliffckerr** [fpsim/fpsim#203]
Currently all locations fail, but for different reasons :)

**Comment by pausz** [comment]
This was me ... The breaker of things and stuff, and hopefully also the mender of merging mayhem. 

A couple of places where empowerment attributes cause failures

1. If `location='kenya'`, execution fails during parameter initialisation in `Sim().__init__`(Introduced by changes in PR #192), due to a `ValueError` in parameter validation in `parameters.py`
```python
 def __init__(self, pars=None, location=None, label=None, track_children=False, **kwargs):
        # Check parameters
        loc_pars = fpp.pars(location)
```
2. If `location` anything else, it fails during (new) attributes initialisation from data. Only `kenya` has data for the new attributes. 

Cliff suggested is to initialise new attributes with None (or perhaps other ["nullable" datatype](https://pandas.pydata.org/docs/user_guide/integer_na.html)).

This could be implemented by:
- Setting the default parameter values of the new attributes to a null type in each `location.py`. Then, handling what to do if attribute  initialisation methods receive a "null type input" in Sim(). The advantage of this approach is that as empowerment data becomes available in each location, we wouldn't have to change anything in `Sim()` or `parameters.pars()`. 
-  Adding empowerment-related keys to the parameter dicts of locations other than kenya, and setting their values to `None`/null dtype. This would handle things on per-location basis, and has the advantage of minimising the number of files to modify.
