### ISSUE TITLE
Docs link broken

### ISSUE THREAD

**Issue by cliffckerr** [fpsim/fpsim#340]
Same issue as here: https://github.com/sciris/sciris/issues/593

The hard link [here](https://docs.idmod.org/projects/fpsim/en/latest/tutorials/T2_scenarios.html) no longer works since it's missing `_autosummary`. But better solution would be to remove `_autosummary` as part of the docs build URL.

@RCarter-IDM, let me know if you know how to do this! Otherwise I'll poke at it.

**Comment by MObrien-IDM** [comment]
FYI that link works for me, @cliffckerr - has this been resolved?

**Comment by MObrien-IDM** [comment]
@cliffckerr @RCarter-IDM closing this issue - feel free to re-open if i'm in the wrong here.

**Comment by cliffckerr** [comment]
Sorry, I meant the hard link _on_ that page:
https://docs.idmod.org/projects/fpsim/en/latest/tutorials/T2_scenarios.html
which is still a 404.

**Comment by RCarter-IDM** [comment]
@cliffckerr, @MObrien-IDM, sorry for delayed reply (apparently I wasn't receiving email GitHub notifications earlier). @cliffckerr, no, I don't know the resolution for this - so, brining in @JSchripsema-IDM who has more experience/knowledge with this.

**Comment by cliffckerr** [comment]
No worries @RCarter-IDM , I think we discussed it already and the solution isn't obvious. But I'll try to get to it before the Symposium :)

**Comment by JSchripsema-IDM** [comment]
@cliffckerr  I'm not sure of the exact issue you're hitting since autosummary should only create the index pages for autogenerated API reference content, not subsections of scenario/tutorial or other manually written RST files. If you want to remove those index pages across all FPsim docs, you can use apidoc instead to generate API reference content (https://romanvm.pythonanywhere.com/post/autodocumenting-your-python-code-sphinx-part-ii-6/). It's what most of the non-Starsim docs use, so you can take a look at emodpy or another package for an example of how to configure it. You can manually create anchor links using the ref directive (https://www.sphinx-doc.org/en/master/tutorial/narrative-documentation.html#adding-cross-references) if you want to just fix the broken link on that page.

**Comment by cliffckerr** [comment]
Sorry, I posted in the wrong URL a second time :joy: 

The current link in the tutorial is:
https://docs.idmod.org/projects/fpsim/en/latest/fpsim.scenarios.html#fpsim.scenarios.Scenario

The actual URL is:
https://docs.idmod.org/projects/fpsim/en/latest/api/_autosummary/fpsim.scenarios.Scenario.html

I want the URL to be:
https://docs.idmod.org/projects/fpsim/en/latest/api/scenarios.Scenario.html

Or equivalently:
https://docs.fpsim.org/api/scenarios.Scenario.html

But yes I'll look at `apidoc` to see if that will fix the issue (and same with the other Starsim+ tools; see identical issue here: https://github.com/sciris/sciris/issues/593, which mentions `emod_api`).

**Comment by JSchripsema-IDM** [comment]
Yeah, I think using `apidoc` will be the solution (emod_api uses that). Autosummary gives you the nice index page (https://docs.idmod.org/projects/fpsim/en/latest/api/_autosummary/fpsim.base.html#module-fpsim.base) but does make the URLs weird. This is an issue that'll only appear in the .ipynb files since you can't use the Python cross-referencing syntax that Sphinx will compile as part of the build and must use the full URL  (syntax would be :py-func:`fpsim.scenarios.Scenarios`)

**Comment by cliffckerr** [comment]
Just did the quick fix. Closed by #445 (well actually #447)
