### ISSUE TITLE
Benchmark and compare fpsim v1.0 and v2.0

### ISSUE THREAD

**Issue by pausz** [fpsim/fpsim#363]
New functionality seems to have slowed down simulations. Quantify by how much, detect time sinks and identify where it can be optimised.

**Comment by emilydriano** [comment]
@pausz @mzimmermann-IDM @robynstuart 

I tested running example_sim.py (kenya as location, 500 agents) in both v1 and v2 and below were my results:

- v1: 4.57s 
- v2: 
       RandomChoice: 4.24s
       SimpleChoice: 39.5s

Clearly the additional logic in the SimpleChoice contraceptive module is significantly increasing the runtime. I did some profiling in Python and found the following results. The first image is sorted by Own Time (time within the function itself) and the second is sorted by Cumulative Time (time in the function and functions it calls). The amount of time in 'docformat' is surprising (it looks like it's a function within scipy?) especially because doing the same profiling with RandomChoice only shows docformat taking up a cumulative .4% whereas here it is 38%...I'm assuming it has something to do with generating the distributions? Besides this potential bottleneck, the next best area of focus I see would be the set_dur_method function, which cumulatively takes up nearly 70% of the runtime. 

![image](https://github.com/fpsim/fpsim/assets/108016846/6e02d0f4-1ab9-4879-9744-25a845886ec1)

![image](https://github.com/fpsim/fpsim/assets/108016846/b52be357-c9ae-42fa-82d8-5dc9e6461666)

**Comment by robynstuart** [comment]
Thanks @emilydriano - I've just looked into this too and `set_dur_method` is definitely the problem.

Couple of options that I can see:
- if drawing from scipy distributions is really so slow, i guess we could cache the values, although i would like to understand why this isn't necessary for any other starsim model
- there are 5 different events that trigger a call to `set_dur_method`: stopping contraception, starting contraception, switching methods, choosing a method 1m postpartum, choosing a method 6m postpartum. So the lines that sample from distributions get called up to `n_timesteps * n_age_bins * 5 * n_methods` times. For a 10 year sim with 5 age bins, that's 27000 calls... 

Looking at the total number of calls (`n_timesteps * n_age_bins * n_events * n_methods`), I think I can remove the `n_age_bins` part. It would help a lot to remove the `n_methods` part too. I am wondering how much predictive power is gained by using separate distributions for each method. We currently have to loop over each method and set the durations based on the distribution for that method, but if we only had to do this once (i.e., if all methods used the same distribution), we'd speed things up a lot. The individual methods could still have different parameters. Would be keen for thoughts @mzimmermann-IDM @MObrien-IDM

**Comment by mzimmermann-IDM** [comment]
@robynstuart or @emilydriano can you point me to where the set_dur_method code is? For some reason it's not coming up when I search... I want to make sure I know what it's doing before talking about this!

**Comment by robynstuart** [comment]
@emilydriano i've made some changes that have sped things up quite a bit: https://github.com/fpsim/fpsim/pull/359

**Comment by robynstuart** [comment]
@mzimmermann-IDM the set_dur_method code is here: https://github.com/fpsim/fpsim/blob/methodtime-jun22/fpsim/methods.py#L221

**Comment by pausz** [comment]
In `fpsim.utils.sample`:
```python
# drawing samples like this 
samples = sps.gamma.rvs(a=par1, scale=par2, size=size)
# instead of 
samples = sps.fisk(c=par1, scale=par2).rvs(size=size)
```
should improve performance. Apparently the latter form [has more overhead](https://stackoverflow.com/questions/43351723/scipy-performance-hit-from-doccer) formatting docstrings.

Though based on profiling stats it does not seem to have huge impact. Ran example_sim.py with SimpleChoice and 10_000 agents. 

`samples = sps.gamma.rvs(a=par1, scale=par2, size=size)`
![image](https://github.com/fpsim/fpsim/assets/1563810/0d5ec795-e04d-4e49-b88c-a45d62696102)
`samples = sps.fisk(c=par1, scale=par2).rvs(size=size)`
![image](https://github.com/fpsim/fpsim/assets/1563810/7fcab613-4c84-422d-9f45-6945cacd4184)

**Comment by pausz** [comment]
@robynstuart @emilydriano 
I've attempted some additional refactoring in `set_dur_method` in #377 that reduced runtime another 20% -- hope I didn't break stuff. 

This draft PR doesn't have to be merged, just illustrates that the increased performance comes from removing the if/elif/else from inside the for loop in set_dur_method. I'm not fond of the many static methods that we now have in SimpleChoice :hands. 

example_sim.py with SimpleChoice and 500 agents, Average runtime (over 10 runs): 3.623 s
example_sim.py with SimpleChoice and 10_000 agents, Average runtime (over 10 runs): 8.8 s
