### ISSUE TITLE
Age-dependent mortality rate - Ethiopia

### ISSUE THREAD

**Issue by aaslinur** [fpsim/fpsim#92]
Find age-dependent mortality rate and trend using World Bank and UN World Pop 2022 data

- Year trend: https://data.worldbank.org/indicator/SP.DYN.CDRT.IN?locations=ET
- UN World Pop 2022: https://population.un.org/wpp/Download/Standard/Mortality/

**Comment by avictorious** [comment]
@aaslinur can you clarify for me what piece of this you'd like help with?  Thanks!

**Comment by aaslinur** [comment]
Hi @avictorious! I have the mortality probability data (mortality_prob_ethiopia), but I still need the mortality trend data, which includes estimates and projections of the crude death rate from 1950-2030 (mortality_trend_ethiopia). Could you help with that trend data?

**Comment by avictorious** [comment]
@aaslinur Sorry for the delay here!  So, the trend data comes just from UN population prospects.  I pulled it from the UN Data Portal and attached here, for 1950-2030.  You just need to create a new csv with just the year and crude death rate.  In Kenya, I normed it around 2010 because my probability data was from that year.  Here is the function you need to copy and adjust for ethiopia.py. https://github.com/fpsim/fpsim/blob/d08f11268269b8e2268e4fc63a760548693cd168/fpsim/locations/kenya.py#L125

[unpopulation_dataportal_cdr_ethiopia.csv](https://github.com/fpsim/fpsim/files/10885116/unpopulation_dataportal_cdr_ethiopia.csv)

Let me know if you need any further guidance!

**Comment by aaslinur** [comment]
Great - that makes sense. The mortality probability data is from 2020 based on UN WP2022 estimates (mx1dt). Thank you for clarifying and sharing the function to update that code.

**Comment by aaslinur** [comment]
Issue Closed: PR #156
