### ISSUE TITLE
Birth spacing preference - Ethiopia

### ISSUE THREAD

**Issue by aaslinur** [fpsim/fpsim#99]
Used to help model women's preference for spacing between births, to be used as needed in calibration. Represents a data insight around population behavior.

- [x] See comments in Kenya calibration for information on setting this parameter.

**Comment by MObrien-IDM** [comment]
@avictorious Can you help with this *after* you've gotten a chance to look at this parameter in general? 

@aaslinur I would add this into ethiopia.py for now with all values = 1 so that it has no effect. Then we can use this later if we need it. I recommend that for all the assumption-based parameters (i.e. exposure)

**Comment by aaslinur** [comment]
Issue Closed: PR #156

**Comment by aaslinur** [comment]
[birth_spacing_dhs.csv](https://github.com/fpsim/fpsim/files/11826473/birth_spacing_dhs.csv)

**Comment by MObrien-IDM** [comment]
Closed
